language: java 
sudo: required
services:
  - docker
jdk:
  - oraclejdk8
  - openjdk11
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4eabeeadee998a77068b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_script:
  - echo MAVEN_OPTS=-Xmx1536m > ~/.mavenrc
  - cd modules/activiti-dependency-check && mvn install -B -V && cd ../..

install: true

# Enable integration tests
# add extra flags for openjdk 11 maven repo download issues: https://stackoverflow.com/a/18326078/4562758
script:
  - mvn verify -B -V -Pdistro,dependency-check -s settings.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

# Send coverage data
after_success:
  bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat **/target/surefire-reports/*.xml | grep -B 1 -A 10 "<error"
  - cat **/target/failsafe-reports/*.xml | grep -B 1 -A 10 "<error"
